In [ ]:
#Assignment no 3

#Question 1
# Program which prints the fibonacci series of a number and write the conditions that nos should not be negative
nos=int(input("Enter the value:"))
if(nos>=0):
 x=0
 y=1
 c=2

 print("Fibonacci series of a number")
 print(x)
 print(y)

 while(c<=nos):
      z=x+y
      print(z)
      x=y
      y=z
      c=c+1
else:
  print("Negative number are not allowed")

Enter the value:-10
Negative number are not allowed

In [ ]:
#Question 2
# Program that finds the distance between 2 points (x1  , y1) and (x2 , y2) using equation formula
import math
x1=int(input("Enter the value for first X cordinate:"))
y1=int(input("Enter the value for first Y cordinate:"))
x2=int(input("Enter the value for second X cordinate:"))
y2=int(input("Enter the value for second Y cordinate:"))

Distance=math.sqrt((x2-x1)**2 + (y2-y1)**2)

print("The distance between two points:",Distance)

Enter the value for first X cordinate:10
Enter the value for first Y cordinate:15
Enter the value for second X cordinate:8
Enter the value for second Y cordinate:12
The distance between two points: 3.605551275463989

In [ ]:
#Question 3
# Program to find the best of two test avearage marks out of three and  test's marks is accepted from the user

test1=int(input("Enter the value for test1:"))
test2=int(input("Enter the value for test2:"))
test3=int(input("Enter the value for test3:"))

if(test1>test2 and test1 > test3):
  total=test1+test2
elif(test2 > test1 and test2 > test3):
  total=test2+test3
else:
  total=test1+test3

avg=total/2
print("best of two test average marks",avg)

Enter the value for test1:20
Enter the value for test2:10
Enter the value for test3:50
best of two test average marks 35.0

In [ ]:
#Question 4
# Program to find the area of triangle and perimeter of triangle

Base=float(input("Enter the base value:"))
Height=float(input("Enter the height value:"))
side1=int(input("Enter the value for side1:"))
side2=int(input("Enter the value for side2:"))
side3=int(input("Enter the value for side3:"))

Area =0.5*Base*Height
Perimeter =side1+side2+side3

print("Area of Triangle",Area)
print("Perimeter of Triangle",Perimeter)

Enter the base value:5
Enter the height value:6
Enter the value for side1:5
Enter the value for side2:4
Enter the value for side3:8
Area of Triangle 15.0
Perimeter of Triangle 17

In [ ]:
#Question 5
# Program to swap the two variables without using the third variable

x=5
y=6

temp=x
x=y
y=temp

print("The value of x after swapping:{}".format(x))
print("The value of y after swapping:{}".format(y))

The value of x after swapping:6
The value of y after swapping:5

In [ ]:
#Question 6
# Write a python program to add two nos which is integer datatype and its result should be displayed as floating datatype
x=5
y=6

print(x)
print(type(x))
print(y)
print(type(y))
#convert integer datatype to floating datatype
x=float(5)
y=float(6)

print(x)
print(type(x))
print(y)
print(type(y))

5
<class 'int'>
6
<class 'int'>
5.0
<class 'float'>
6.0
<class 'float'>

In [ ]:
#Question 7
# Program to generate student Result . Accept marks of five subject and display the result according to following conditions:-

# Percentage     Division
# >=75             First Class with Distinction
# >=60 and <75     First Class
# >=45 and <60     Second Class
# >=40 and <45     Pass
# <40              FAIL

m1=int(input("Enter the marks of Maths:"))
m2=int(input("Enter the marks of English:"))
m3=int(input("Enter the marks of History:"))
m4=int(input("Enter the marks of Science:"))
m5=int(input("Enter the marks of Geography:"))

Percentage=(m1+m2+m3+m4+m5)/500*100
if(Percentage>=75):
  print("First Class and Distinction")

elif(Percentage>=60 and Percentage<75):
  print("First Class")

elif(Percentage>=45 and Percentage<60):
  print("Second Class")

elif(Percentage>=40 and Percentage<45):
  print("Pass")

elif(Percentage<40):
  print("Fail")

else:
  print("Result not diaplay")

Enter the marks of Maths:56
Enter the marks of English:60
Enter the marks of History:78
Enter the marks of Science:52
Enter the marks of Geography:65
First Class

In [11]:
#Question 8
# Program to print the following pattern

# *
# * *
# * * *
# * * * *

i=1
while(i<5):
  j=1
  while(j<(i+1)):
    print("*", end='')
    j=j+1
  i=i+1
  print()

*
**
***
****

In [18]:
#Question 9
# Program to print the table of 6 I want O/P as in given format
# 6 * 1 = 6
# 6 * 2 = 12
# 6 * 3 = 18
# .
# .
# .
# .
# 6 * 10 = 60

num=6

for i in range (1,11):
  print(num, 'x', i,'=',num*i)

6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60

In [38]:
#Question 10
# Program which accpets 5 integers values and print "DUPLICATES" if any of the values entered are repeated otherwise it prints
# "ALL UNIQUE" . Let 5 integers are (32 , 45 , 90 ,45 ,6 )
#  Now you can se dupliactes is 45 and uniques are 32 , 90 , 6 so my output should be in below format

# DUPLICATE : 45
# UNIQUE : 32
# UNIQUE : 90
# UNIQUE  : 6
values = []
i = 0

while i < 5:
    value = int(input(f"Enter integer value {i+1}: "))

    if value in values:
        print(f"DUPLICATE: {value}")
    else:
        print(f"UNIQUE: {value}")
        values.append(value)
        i += 1

Enter integer value 1: 32
UNIQUE: 32
Enter integer value 2: 45
UNIQUE: 45
Enter integer value 3: 90
UNIQUE: 90
Enter integer value 4: 45
DUPLICATE: 45
Enter integer value 4: 6
UNIQUE: 6
Enter integer value 5: 45
DUPLICATE: 45
Enter integer value 5: 12
UNIQUE: 12